FROM python:3.13
WORKDIR /app

COPY backend/crc-api/api-container/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt 

COPY backend/crc-api/api-container/ ./

EXPOSE 8000 

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"] 
